/**
 * Galería de Personajes Bíblicos.
 *
 * Reúne más de 150 personajes nombrados a lo largo de toda la Biblia,
 * de Génesis a Apocalipsis, agrupados por época/sección. El propósito es
 * traer estas figuras del pasado bíblico al presente: cada una aparece
 * también en las preguntas de trivia (js/questions.js) y varias inspiran
 * las enseñanzas aplicadas (js/teachings.js).
 *
 * Nota honesta: la Biblia menciona miles de nombres, muchos de ellos solo
 * en genealogías. Esta galería no pretende ser una lista exhaustiva letra
 * por letra, pero cubre de forma amplia y representativa a los personajes
 * con un papel narrativo en cada libro y época del relato bíblico.
 */

const CHARACTER_GALLERY = [
  {
    era: "Orígenes: Creación y primeros descendientes",
    ref: "Génesis 1–11",
    people: [
      { name: "Adán", desc: "El primer hombre, formado por Dios del polvo de la tierra." },
      { name: "Eva", desc: "La primera mujer, madre de toda la humanidad." },
      { name: "Caín", desc: "Hijo mayor de Adán y Eva; mató a su hermano Abel." },
      { name: "Abel", desc: "Segundo hijo de Adán y Eva, pastor de ovejas." },
      { name: "Set", desc: "Hijo de Adán y Eva nacido tras la muerte de Abel." },
      { name: "Enós", desc: "Hijo de Set, nieto de Adán." },
      { name: "Enoc", desc: "Caminó con Dios y no experimentó la muerte." },
      { name: "Matusalén", desc: "El hombre más longevo de la Biblia: 969 años." },
      { name: "Lamec", desc: "Padre de Noé." },
      { name: "Noé", desc: "Construyó el arca y sobrevivió al diluvio." },
      { name: "Sem", desc: "Hijo de Noé, antepasado de los pueblos semitas." },
      { name: "Cam", desc: "Hijo de Noé." },
      { name: "Jafet", desc: "Hijo de Noé." },
      { name: "Nimrod", desc: "Poderoso cazador, fundador de reinos como Babel." },
      { name: "Taré", desc: "Padre de Abraham." },
    ],
  },
  {
    era: "Los Patriarcas y sus familias",
    ref: "Génesis 12–50",
    people: [
      { name: "Abraham", desc: "Padre de la fe; salió de su tierra confiando en la promesa de Dios." },
      { name: "Sara", desc: "Esposa de Abraham, madre de Isaac en su vejez." },
      { name: "Lot", desc: "Sobrino de Abraham; vivió en Sodoma." },
      { name: "Agar", desc: "Sierva de Sara, madre de Ismael." },
      { name: "Ismael", desc: "Hijo de Abraham y Agar." },
      { name: "Isaac", desc: "Hijo de la promesa, casi ofrecido en sacrificio por Abraham." },
      { name: "Rebeca", desc: "Esposa de Isaac, madre de Esaú y Jacob." },
      { name: "Esaú", desc: "Hijo mayor de Isaac; vendió su primogenitura." },
      { name: "Jacob (Israel)", desc: "Hijo menor de Isaac, padre de las doce tribus de Israel." },
      { name: "Labán", desc: "Suegro y tío de Jacob." },
      { name: "Lea", desc: "Primera esposa de Jacob." },
      { name: "Raquel", desc: "Esposa amada de Jacob, madre de José y Benjamín." },
      { name: "Bilha", desc: "Sierva de Raquel, madre de Dan y Neftalí." },
      { name: "Zilpa", desc: "Sierva de Lea, madre de Gad y Aser." },
      { name: "Rubén", desc: "Hijo mayor de Jacob, cabeza de una de las doce tribus." },
      { name: "Simeón", desc: "Hijo de Jacob y Lea." },
      { name: "Leví", desc: "Hijo de Jacob; su tribu sería la de los sacerdotes." },
      { name: "Judá", desc: "Hijo de Jacob; de su tribu descendería el rey David." },
      { name: "Isacar", desc: "Hijo de Jacob y Lea." },
      { name: "Zabulón", desc: "Hijo de Jacob y Lea." },
      { name: "Dan", desc: "Hijo de Jacob y Bilha." },
      { name: "Neftalí", desc: "Hijo de Jacob y Bilha." },
      { name: "Gad", desc: "Hijo de Jacob y Zilpa." },
      { name: "Aser", desc: "Hijo de Jacob y Zilpa." },
      { name: "Benjamín", desc: "Hijo menor de Jacob y Raquel." },
      { name: "Dina", desc: "Hija de Jacob y Lea." },
      { name: "Tamar (nuera de Judá)", desc: "Antepasada de David, mencionada en la genealogía de Jesús." },
      { name: "José", desc: "Vendido por sus hermanos; llegó a ser gobernador de Egipto." },
      { name: "Potifar", desc: "Oficial egipcio, amo de José." },
      { name: "Asenat", desc: "Esposa egipcia de José." },
      { name: "Efraín", desc: "Hijo de José, cabeza de tribu." },
      { name: "Manasés", desc: "Hijo de José, cabeza de tribu." },
      { name: "Melquisedec", desc: "Rey-sacerdote de Salem que bendijo a Abraham." },
    ],
  },
  {
    era: "Éxodo y el desierto",
    ref: "Éxodo – Deuteronomio",
    people: [
      { name: "Moisés", desc: "Libertador de Israel; recibió la Ley en el monte Sinaí." },
      { name: "Aarón", desc: "Hermano de Moisés, primer sumo sacerdote de Israel." },
      { name: "Miriam", desc: "Hermana de Moisés y Aarón, profetisa." },
      { name: "Jetro", desc: "Suegro de Moisés, sacerdote de Madián." },
      { name: "Séfora", desc: "Esposa de Moisés." },
      { name: "Josué", desc: "Sucesor de Moisés; guio la conquista de Canaán." },
      { name: "Caleb", desc: "Espía fiel; heredó tierra en Canaán por su fidelidad." },
      { name: "Coré, Datán y Abiram", desc: "Líderes de una rebelión contra Moisés y Aarón." },
      { name: "Balaam", desc: "Profeta pagano cuya burra habló para advertirle." },
      { name: "Balac", desc: "Rey de Moab que contrató a Balaam para maldecir a Israel." },
      { name: "Finees", desc: "Nieto de Aarón, celoso por la santidad de Dios." },
      { name: "Nadab y Abiú", desc: "Hijos de Aarón; murieron por ofrecer fuego extraño." },
      { name: "Bezaleel", desc: "Artesano que construyó el tabernáculo." },
    ],
  },
  {
    era: "Conquista y Jueces",
    ref: "Josué – Rut",
    people: [
      { name: "Rahab", desc: "Protegió a los espías israelitas en Jericó." },
      { name: "Acán", desc: "Su desobediencia costó una derrota en Hai." },
      { name: "Otoniel", desc: "Primer juez de Israel." },
      { name: "Aod", desc: "Juez zurdo que liberó a Israel de Moab." },
      { name: "Débora", desc: "Jueza y profetisa que gobernó a Israel." },
      { name: "Barac", desc: "General que luchó junto a Débora." },
      { name: "Jael", desc: "Mató al general enemigo Sísara." },
      { name: "Gedeón", desc: "Juez que venció a los madianitas con solo 300 hombres." },
      { name: "Abimelec", desc: "Hijo de Gedeón, rey usurpador." },
      { name: "Jefté", desc: "Juez que hizo un voto trágico a Dios." },
      { name: "Sansón", desc: "Juez de gran fuerza, traicionado por Dalila." },
      { name: "Dalila", desc: "Descubrió el secreto de la fuerza de Sansón." },
      { name: "Rut", desc: "Moabita fiel, bisabuela del rey David." },
      { name: "Noemí", desc: "Suegra de Rut." },
      { name: "Booz", desc: "Pariente redentor que se casó con Rut." },
    ],
  },
  {
    era: "Reino unido: Samuel, Saúl, David y Salomón",
    ref: "1–2 Samuel, 1 Reyes",
    people: [
      { name: "Elí", desc: "Sacerdote y juez; mentor del joven Samuel." },
      { name: "Ana", desc: "Madre de Samuel, mujer de oración constante." },
      { name: "Samuel", desc: "Último juez y profeta; ungió a Saúl y a David." },
      { name: "Saúl", desc: "Primer rey de Israel." },
      { name: "Jonatán", desc: "Hijo de Saúl, amigo leal de David." },
      { name: "Mical", desc: "Hija de Saúl, esposa de David." },
      { name: "David", desc: "Pastor que llegó a ser rey; venció al gigante Goliat." },
      { name: "Goliat", desc: "Gigante filisteo derrotado por David." },
      { name: "Abigail", desc: "Esposa sabia que luego se casó con David." },
      { name: "Betsabé", desc: "Esposa de David, madre de Salomón." },
      { name: "Natán", desc: "Profeta que confrontó a David por su pecado." },
      { name: "Absalón", desc: "Hijo de David que se rebeló contra él." },
      { name: "Joab", desc: "General del ejército de David." },
      { name: "Abner", desc: "General del ejército de Saúl." },
      { name: "Salomón", desc: "Rey sabio, constructor del Templo de Jerusalén." },
      { name: "La reina de Sabá", desc: "Visitó a Salomón atraída por su sabiduría." },
    ],
  },
  {
    era: "Reinos divididos y sus profetas",
    ref: "1–2 Reyes, 1–2 Crónicas",
    people: [
      { name: "Roboam", desc: "Hijo de Salomón; su reinado causó la división del reino." },
      { name: "Jeroboam", desc: "Primer rey del reino del norte, Israel." },
      { name: "Elías", desc: "Profeta que enfrentó a los profetas de Baal en el Carmelo." },
      { name: "Acab", desc: "Rey de Israel, esposo de Jezabel." },
      { name: "Jezabel", desc: "Reina que promovió la adoración de Baal." },
      { name: "Abdías (mayordomo de Acab)", desc: "Protegió a cien profetas de la persecución." },
      { name: "Eliseo", desc: "Sucesor de Elías; realizó muchos milagros." },
      { name: "Naamán", desc: "General sirio sanado de lepra por Eliseo." },
      { name: "Giezi", desc: "Siervo de Eliseo, castigado por su codicia." },
      { name: "Jehú", desc: "Rey que eliminó a la casa de Acab." },
      { name: "Atalía", desc: "Reina usurpadora de Judá." },
      { name: "Joás", desc: "Rey niño rescatado de Atalía." },
      { name: "Ezequías", desc: "Rey reformador de Judá." },
      { name: "Manasés", desc: "Rey de Judá que se arrepintió tras un cautiverio." },
      { name: "Josías", desc: "Rey que restauró la adoración a Dios en Judá." },
      { name: "Hulda", desc: "Profetisa que confirmó el libro de la Ley hallado en el Templo." },
    ],
  },
  {
    era: "Exilio y regreso",
    ref: "Esdras, Nehemías, Ester, Daniel",
    people: [
      { name: "Nabucodonosor", desc: "Rey de Babilonia; tuvo un sueño interpretado por Daniel." },
      { name: "Belsasar", desc: "Rey que vio la escritura en la pared: 'Mene, Mene, Tekel, Uparsin'." },
      { name: "Darío", desc: "Rey persa bajo cuyo reinado Daniel fue arrojado a los leones." },
      { name: "Ciro", desc: "Rey persa que permitió el regreso de los judíos a Jerusalén." },
      { name: "Zorobabel", desc: "Líder que dirigió la reconstrucción del Templo." },
      { name: "Esdras", desc: "Sacerdote y escriba que enseñó la Ley al pueblo." },
      { name: "Nehemías", desc: "Reconstruyó las murallas de Jerusalén." },
      { name: "Ester", desc: "Reina judía que arriesgó su vida para salvar a su pueblo." },
      { name: "Mardoqueo", desc: "Primo y padre adoptivo de Ester." },
      { name: "Amán", desc: "Enemigo de los judíos; planeó su exterminio." },
      { name: "Asuero", desc: "Rey persa, esposo de Ester." },
      { name: "Vasti", desc: "Reina destituida antes de Ester." },
    ],
  },
  {
    era: "Sabiduría, Salmos y profetas menores",
    ref: "Job, Salmos, Proverbios, profetas menores",
    people: [
      { name: "Job", desc: "Hombre justo de la tierra de Uz; mantuvo su fe en gran sufrimiento." },
      { name: "Elifaz, Bildad y Zofar", desc: "Amigos de Job que lo visitaron para 'consolarlo'." },
      { name: "Eliú", desc: "El más joven de los amigos de Job, habló al final." },
      { name: "Asaf", desc: "Músico y salmista, autor de varios Salmos." },
      { name: "Agur", desc: "Autor de los dichos de Proverbios 30." },
      { name: "Oseas", desc: "Profeta cuyo matrimonio simbolizó el amor de Dios por Israel." },
      { name: "Joel", desc: "Profeta que anunció una plaga de langostas sobre Judá." },
      { name: "Amós", desc: "Pastor de Tecoa llamado a profetizar." },
      { name: "Abdías (profeta)", desc: "Autor del libro más corto del Antiguo Testamento." },
      { name: "Jonás", desc: "Profeta tragado por un gran pez tras huir de su misión." },
      { name: "Miqueas", desc: "Anunció que el Mesías nacería en Belén." },
      { name: "Nahúm", desc: "Profetizó la caída de Nínive." },
      { name: "Habacuc", desc: "Cuestionó a Dios sobre la justicia y esperó su respuesta." },
      { name: "Sofonías", desc: "Profeta que anunció el día del Señor." },
      { name: "Hageo", desc: "Animó al pueblo a reconstruir el Templo." },
      { name: "Zacarías (profeta)", desc: "Tuvo visiones sobre la restauración de Jerusalén." },
      { name: "Malaquías", desc: "Autor del último libro del Antiguo Testamento." },
    ],
  },
  {
    era: "Los Evangelios: la vida de Jesús",
    ref: "Mateo, Marcos, Lucas, Juan",
    people: [
      { name: "María", desc: "Madre de Jesús." },
      { name: "José (esposo de María)", desc: "Padre adoptivo de Jesús, carpintero de Nazaret." },
      { name: "Zacarías y Elisabet", desc: "Padres de Juan el Bautista." },
      { name: "Juan el Bautista", desc: "Precursor de Jesús; bautizó en el río Jordán." },
      { name: "Jesús", desc: "El Mesías; centro de los cuatro Evangelios." },
      { name: "Pedro", desc: "Pescador; líder entre los doce apóstoles." },
      { name: "Andrés", desc: "Hermano de Pedro, también apóstol." },
      { name: "Santiago (hijo de Zebedeo)", desc: "Apóstol, hermano de Juan." },
      { name: "Juan (apóstol)", desc: "El 'discípulo amado'; escribió un Evangelio y Apocalipsis." },
      { name: "Felipe (apóstol)", desc: "Uno de los doce apóstoles." },
      { name: "Bartolomé (Natanael)", desc: "Apóstol descrito como 'sin engaño'." },
      { name: "Tomás", desc: "Apóstol que dudó de la resurrección hasta ver las heridas." },
      { name: "Mateo", desc: "Recaudador de impuestos llamado a ser apóstol." },
      { name: "Santiago (hijo de Alfeo)", desc: "Uno de los doce apóstoles." },
      { name: "Tadeo", desc: "Uno de los doce apóstoles." },
      { name: "Simón el Zelote", desc: "Uno de los doce apóstoles." },
      { name: "Judas Iscariote", desc: "Traicionó a Jesús por 30 monedas de plata." },
      { name: "María Magdalena", desc: "Discípula fiel; primer testigo de la resurrección." },
      { name: "Marta", desc: "Hermana de Lázaro y María de Betania." },
      { name: "María de Betania", desc: "Ungió los pies de Jesús con perfume costoso." },
      { name: "Lázaro", desc: "Resucitado por Jesús después de cuatro días de muerto." },
      { name: "Nicodemo", desc: "Fariseo que buscó a Jesús de noche." },
      { name: "La mujer samaritana", desc: "Habló con Jesús junto a un pozo." },
      { name: "Zaqueo", desc: "Recaudador de impuestos transformado por Jesús." },
      { name: "Bartimeo", desc: "Mendigo ciego sanado por Jesús." },
      { name: "El joven rico", desc: "No pudo dejar sus riquezas para seguir a Jesús." },
      { name: "Poncio Pilato", desc: "Gobernador romano que sentenció a Jesús." },
      { name: "Herodes el Grande", desc: "Rey que ordenó matar a los niños de Belén." },
      { name: "Herodes Antipas", desc: "Gobernante que interrogó a Jesús." },
      { name: "Herodías y Salomé", desc: "Causaron la muerte de Juan el Bautista." },
      { name: "Caifás y Anás", desc: "Sumos sacerdotes que juzgaron a Jesús." },
      { name: "Simón de Cirene", desc: "Cargó la cruz de Jesús." },
      { name: "José de Arimatea", desc: "Ofreció su propia tumba para el cuerpo de Jesús." },
      { name: "Barrabás", desc: "Preso liberado en lugar de Jesús." },
      { name: "El buen ladrón", desc: "Creyó en Jesús mientras ambos morían en la cruz." },
    ],
  },
  {
    era: "Hechos y la iglesia primitiva",
    ref: "Hechos, cartas del Nuevo Testamento",
    people: [
      { name: "Matías", desc: "Reemplazó a Judas Iscariote entre los doce." },
      { name: "Esteban", desc: "Primer mártir cristiano, apedreado por su fe." },
      { name: "Felipe el evangelista", desc: "Bautizó al eunuco etíope." },
      { name: "Simón el mago", desc: "Quiso comprar el poder del Espíritu Santo." },
      { name: "El eunuco etíope", desc: "Funcionario bautizado por Felipe en el camino a Gaza." },
      { name: "Cornelio", desc: "Primer gentil bautizado, tras la visión de un ángel." },
      { name: "Ananías de Damasco", desc: "Sanó a Saulo de su ceguera tras su conversión." },
      { name: "Ananías y Safira", desc: "Mintieron al Espíritu Santo sobre el dinero de una venta." },
      { name: "Bernabé", desc: "Compañero de misión de Pablo, 'hijo de consolación'." },
      { name: "Pablo (Saulo de Tarso)", desc: "Perseguidor de cristianos convertido en gran misionero." },
      { name: "Silas", desc: "Compañero de viaje de Pablo." },
      { name: "Timoteo", desc: "Joven discípulo y colaborador cercano de Pablo." },
      { name: "Tito", desc: "Colaborador de Pablo, encargado de la iglesia en Creta." },
      { name: "Lucas", desc: "Médico; autor del Evangelio de Lucas y de Hechos." },
      { name: "Juan Marcos", desc: "Autor del Evangelio de Marcos." },
      { name: "Priscila y Aquila", desc: "Matrimonio que instruyó más plenamente a Apolos." },
      { name: "Apolos", desc: "Predicador elocuente de Alejandría." },
      { name: "Lidia", desc: "Primera convertida en Europa, en la ciudad de Filipos." },
      { name: "Dorcas (Tabita)", desc: "Discípula conocida por su generosidad y caridad." },
      { name: "Agabo", desc: "Profeta que anunció el arresto de Pablo en Jerusalén." },
      { name: "Sergio Paulo", desc: "Procónsul romano que creyó en el evangelio." },
      { name: "Elimas", desc: "Mago que se opuso a la predicación de Pablo." },
      { name: "Gamaliel", desc: "Maestro de la Ley que defendió a los apóstoles ante el Sanedrín." },
      { name: "Herodes Agripa I", desc: "Rey que persiguió a la iglesia primitiva." },
      { name: "Herodes Agripa II y Berenice", desc: "Escucharon la defensa de Pablo." },
      { name: "Félix y Festo", desc: "Gobernadores romanos que juzgaron el caso de Pablo." },
      { name: "Onésimo", desc: "Esclavo fugitivo, tema central de la carta a Filemón." },
      { name: "Filemón", desc: "Dueño cristiano de Onésimo, destinatario de una carta de Pablo." },
      { name: "Epafrodito", desc: "Mensajero y colaborador cercano de Pablo." },
      { name: "Aristarco y Trófimo", desc: "Compañeros de viaje de Pablo." },
      { name: "Tíquico", desc: "Mensajero de confianza de Pablo." },
      { name: "Andrónico y Junias", desc: "Cristianos notables mencionados en la carta a los Romanos." },
      { name: "Febe", desc: "Diaconisa que llevó la carta de Pablo a los Romanos." },
    ],
  },
];
