/**
 * Galería de Personajes Bíblicos.
 *
 * Reúne más de 150 personajes nombrados a lo largo de toda la Biblia,
 * de Génesis a Apocalipsis, agrupados por época/sección. El propósito es
 * traer estas figuras del pasado bíblico al presente: cada una aparece
 * también en las preguntas de trivia (js/questions.js) y varias inspiran
 * las enseñanzas aplicadas (js/teachings.js).
 *
 * Nota honesta: la Biblia menciona miles de nombres, muchos de ellos solo
 * en genealogías. Esta galería no pretende ser una lista exhaustiva letra
 * por letra, pero cubre de forma amplia y representativa a los personajes
 * con un papel narrativo en cada libro y época del relato bíblico.
 */

const CHARACTER_GALLERY_ES = [
  {
    era: "Orígenes: Creación y primeros descendientes",
    ref: "Génesis 1–11",
    people: [
      { name: "Adán", desc: "El primer hombre, formado por Dios del polvo de la tierra." },
      { name: "Eva", desc: "La primera mujer, madre de toda la humanidad." },
      { name: "Caín", desc: "Hijo mayor de Adán y Eva; mató a su hermano Abel." },
      { name: "Abel", desc: "Segundo hijo de Adán y Eva, pastor de ovejas." },
      { name: "Set", desc: "Hijo de Adán y Eva nacido tras la muerte de Abel." },
      { name: "Enós", desc: "Hijo de Set, nieto de Adán." },
      { name: "Enoc", desc: "Caminó con Dios y no experimentó la muerte." },
      { name: "Matusalén", desc: "El hombre más longevo de la Biblia: 969 años." },
      { name: "Lamec", desc: "Padre de Noé." },
      { name: "Noé", desc: "Construyó el arca y sobrevivió al diluvio." },
      { name: "Sem", desc: "Hijo de Noé, antepasado de los pueblos semitas." },
      { name: "Cam", desc: "Hijo de Noé." },
      { name: "Jafet", desc: "Hijo de Noé." },
      { name: "Nimrod", desc: "Poderoso cazador, fundador de reinos como Babel." },
      { name: "Taré", desc: "Padre de Abraham." },
    ],
  },
  {
    era: "Los Patriarcas y sus familias",
    ref: "Génesis 12–50",
    people: [
      { name: "Abraham", desc: "Padre de la fe; salió de su tierra confiando en la promesa de Dios." },
      { name: "Sara", desc: "Esposa de Abraham, madre de Isaac en su vejez." },
      { name: "Lot", desc: "Sobrino de Abraham; vivió en Sodoma." },
      { name: "Agar", desc: "Sierva de Sara, madre de Ismael." },
      { name: "Ismael", desc: "Hijo de Abraham y Agar." },
      { name: "Isaac", desc: "Hijo de la promesa, casi ofrecido en sacrificio por Abraham." },
      { name: "Rebeca", desc: "Esposa de Isaac, madre de Esaú y Jacob." },
      { name: "Esaú", desc: "Hijo mayor de Isaac; vendió su primogenitura." },
      { name: "Jacob (Israel)", desc: "Hijo menor de Isaac, padre de las doce tribus de Israel." },
      { name: "Labán", desc: "Suegro y tío de Jacob." },
      { name: "Lea", desc: "Primera esposa de Jacob." },
      { name: "Raquel", desc: "Esposa amada de Jacob, madre de José y Benjamín." },
      { name: "Bilha", desc: "Sierva de Raquel, madre de Dan y Neftalí." },
      { name: "Zilpa", desc: "Sierva de Lea, madre de Gad y Aser." },
      { name: "Rubén", desc: "Hijo mayor de Jacob, cabeza de una de las doce tribus." },
      { name: "Simeón", desc: "Hijo de Jacob y Lea." },
      { name: "Leví", desc: "Hijo de Jacob; su tribu sería la de los sacerdotes." },
      { name: "Judá", desc: "Hijo de Jacob; de su tribu descendería el rey David." },
      { name: "Isacar", desc: "Hijo de Jacob y Lea." },
      { name: "Zabulón", desc: "Hijo de Jacob y Lea." },
      { name: "Dan", desc: "Hijo de Jacob y Bilha." },
      { name: "Neftalí", desc: "Hijo de Jacob y Bilha." },
      { name: "Gad", desc: "Hijo de Jacob y Zilpa." },
      { name: "Aser", desc: "Hijo de Jacob y Zilpa." },
      { name: "Benjamín", desc: "Hijo menor de Jacob y Raquel." },
      { name: "Dina", desc: "Hija de Jacob y Lea." },
      { name: "Tamar (nuera de Judá)", desc: "Antepasada de David, mencionada en la genealogía de Jesús." },
      { name: "José", desc: "Vendido por sus hermanos; llegó a ser gobernador de Egipto." },
      { name: "Potifar", desc: "Oficial egipcio, amo de José." },
      { name: "Asenat", desc: "Esposa egipcia de José." },
      { name: "Efraín", desc: "Hijo de José, cabeza de tribu." },
      { name: "Manasés", desc: "Hijo de José, cabeza de tribu." },
      { name: "Melquisedec", desc: "Rey-sacerdote de Salem que bendijo a Abraham." },
    ],
  },
  {
    era: "Éxodo y el desierto",
    ref: "Éxodo – Deuteronomio",
    people: [
      { name: "Moisés", desc: "Libertador de Israel; recibió la Ley en el monte Sinaí." },
      { name: "Aarón", desc: "Hermano de Moisés, primer sumo sacerdote de Israel." },
      { name: "Miriam", desc: "Hermana de Moisés y Aarón, profetisa." },
      { name: "Jetro", desc: "Suegro de Moisés, sacerdote de Madián." },
      { name: "Séfora", desc: "Esposa de Moisés." },
      { name: "Josué", desc: "Sucesor de Moisés; guio la conquista de Canaán." },
      { name: "Caleb", desc: "Espía fiel; heredó tierra en Canaán por su fidelidad." },
      { name: "Coré, Datán y Abiram", desc: "Líderes de una rebelión contra Moisés y Aarón." },
      { name: "Balaam", desc: "Profeta pagano cuya burra habló para advertirle." },
      { name: "Balac", desc: "Rey de Moab que contrató a Balaam para maldecir a Israel." },
      { name: "Finees", desc: "Nieto de Aarón, celoso por la santidad de Dios." },
      { name: "Nadab y Abiú", desc: "Hijos de Aarón; murieron por ofrecer fuego extraño." },
      { name: "Bezaleel", desc: "Artesano que construyó el tabernáculo." },
    ],
  },
  {
    era: "Conquista y Jueces",
    ref: "Josué – Rut",
    people: [
      { name: "Rahab", desc: "Protegió a los espías israelitas en Jericó." },
      { name: "Acán", desc: "Su desobediencia costó una derrota en Hai." },
      { name: "Otoniel", desc: "Primer juez de Israel." },
      { name: "Aod", desc: "Juez zurdo que liberó a Israel de Moab." },
      { name: "Débora", desc: "Jueza y profetisa que gobernó a Israel." },
      { name: "Barac", desc: "General que luchó junto a Débora." },
      { name: "Jael", desc: "Mató al general enemigo Sísara." },
      { name: "Gedeón", desc: "Juez que venció a los madianitas con solo 300 hombres." },
      { name: "Abimelec", desc: "Hijo de Gedeón, rey usurpador." },
      { name: "Jefté", desc: "Juez que hizo un voto trágico a Dios." },
      { name: "Sansón", desc: "Juez de gran fuerza, traicionado por Dalila." },
      { name: "Dalila", desc: "Descubrió el secreto de la fuerza de Sansón." },
      { name: "Rut", desc: "Moabita fiel, bisabuela del rey David." },
      { name: "Noemí", desc: "Suegra de Rut." },
      { name: "Booz", desc: "Pariente redentor que se casó con Rut." },
    ],
  },
  {
    era: "Reino unido: Samuel, Saúl, David y Salomón",
    ref: "1–2 Samuel, 1 Reyes",
    people: [
      { name: "Elí", desc: "Sacerdote y juez; mentor del joven Samuel." },
      { name: "Ana", desc: "Madre de Samuel, mujer de oración constante." },
      { name: "Samuel", desc: "Último juez y profeta; ungió a Saúl y a David." },
      { name: "Saúl", desc: "Primer rey de Israel." },
      { name: "Jonatán", desc: "Hijo de Saúl, amigo leal de David." },
      { name: "Mical", desc: "Hija de Saúl, esposa de David." },
      { name: "David", desc: "Pastor que llegó a ser rey; venció al gigante Goliat." },
      { name: "Goliat", desc: "Gigante filisteo derrotado por David." },
      { name: "Abigail", desc: "Esposa sabia que luego se casó con David." },
      { name: "Betsabé", desc: "Esposa de David, madre de Salomón." },
      { name: "Natán", desc: "Profeta que confrontó a David por su pecado." },
      { name: "Absalón", desc: "Hijo de David que se rebeló contra él." },
      { name: "Joab", desc: "General del ejército de David." },
      { name: "Abner", desc: "General del ejército de Saúl." },
      { name: "Salomón", desc: "Rey sabio, constructor del Templo de Jerusalén." },
      { name: "La reina de Sabá", desc: "Visitó a Salomón atraída por su sabiduría." },
    ],
  },
  {
    era: "Reinos divididos y sus profetas",
    ref: "1–2 Reyes, 1–2 Crónicas",
    people: [
      { name: "Roboam", desc: "Hijo de Salomón; su reinado causó la división del reino." },
      { name: "Jeroboam", desc: "Primer rey del reino del norte, Israel." },
      { name: "Elías", desc: "Profeta que enfrentó a los profetas de Baal en el Carmelo." },
      { name: "Acab", desc: "Rey de Israel, esposo de Jezabel." },
      { name: "Jezabel", desc: "Reina que promovió la adoración de Baal." },
      { name: "Abdías (mayordomo de Acab)", desc: "Protegió a cien profetas de la persecución." },
      { name: "Eliseo", desc: "Sucesor de Elías; realizó muchos milagros." },
      { name: "Naamán", desc: "General sirio sanado de lepra por Eliseo." },
      { name: "Giezi", desc: "Siervo de Eliseo, castigado por su codicia." },
      { name: "Jehú", desc: "Rey que eliminó a la casa de Acab." },
      { name: "Atalía", desc: "Reina usurpadora de Judá." },
      { name: "Joás", desc: "Rey niño rescatado de Atalía." },
      { name: "Ezequías", desc: "Rey reformador de Judá." },
      { name: "Manasés", desc: "Rey de Judá que se arrepintió tras un cautiverio." },
      { name: "Josías", desc: "Rey que restauró la adoración a Dios en Judá." },
      { name: "Hulda", desc: "Profetisa que confirmó el libro de la Ley hallado en el Templo." },
    ],
  },
  {
    era: "Exilio y regreso",
    ref: "Esdras, Nehemías, Ester, Daniel",
    people: [
      { name: "Nabucodonosor", desc: "Rey de Babilonia; tuvo un sueño interpretado por Daniel." },
      { name: "Belsasar", desc: "Rey que vio la escritura en la pared: 'Mene, Mene, Tekel, Uparsin'." },
      { name: "Darío", desc: "Rey persa bajo cuyo reinado Daniel fue arrojado a los leones." },
      { name: "Ciro", desc: "Rey persa que permitió el regreso de los judíos a Jerusalén." },
      { name: "Zorobabel", desc: "Líder que dirigió la reconstrucción del Templo." },
      { name: "Esdras", desc: "Sacerdote y escriba que enseñó la Ley al pueblo." },
      { name: "Nehemías", desc: "Reconstruyó las murallas de Jerusalén." },
      { name: "Ester", desc: "Reina judía que arriesgó su vida para salvar a su pueblo." },
      { name: "Mardoqueo", desc: "Primo y padre adoptivo de Ester." },
      { name: "Amán", desc: "Enemigo de los judíos; planeó su exterminio." },
      { name: "Asuero", desc: "Rey persa, esposo de Ester." },
      { name: "Vasti", desc: "Reina destituida antes de Ester." },
    ],
  },
  {
    era: "Sabiduría, Salmos y profetas menores",
    ref: "Job, Salmos, Proverbios, profetas menores",
    people: [
      { name: "Job", desc: "Hombre justo de la tierra de Uz; mantuvo su fe en gran sufrimiento." },
      { name: "Elifaz, Bildad y Zofar", desc: "Amigos de Job que lo visitaron para 'consolarlo'." },
      { name: "Eliú", desc: "El más joven de los amigos de Job, habló al final." },
      { name: "Asaf", desc: "Músico y salmista, autor de varios Salmos." },
      { name: "Agur", desc: "Autor de los dichos de Proverbios 30." },
      { name: "Oseas", desc: "Profeta cuyo matrimonio simbolizó el amor de Dios por Israel." },
      { name: "Joel", desc: "Profeta que anunció una plaga de langostas sobre Judá." },
      { name: "Amós", desc: "Pastor de Tecoa llamado a profetizar." },
      { name: "Abdías (profeta)", desc: "Autor del libro más corto del Antiguo Testamento." },
      { name: "Jonás", desc: "Profeta tragado por un gran pez tras huir de su misión." },
      { name: "Miqueas", desc: "Anunció que el Mesías nacería en Belén." },
      { name: "Nahúm", desc: "Profetizó la caída de Nínive." },
      { name: "Habacuc", desc: "Cuestionó a Dios sobre la justicia y esperó su respuesta." },
      { name: "Sofonías", desc: "Profeta que anunció el día del Señor." },
      { name: "Hageo", desc: "Animó al pueblo a reconstruir el Templo." },
      { name: "Zacarías (profeta)", desc: "Tuvo visiones sobre la restauración de Jerusalén." },
      { name: "Malaquías", desc: "Autor del último libro del Antiguo Testamento." },
    ],
  },
  {
    era: "Los Evangelios: la vida de Jesús",
    ref: "Mateo, Marcos, Lucas, Juan",
    people: [
      { name: "María", desc: "Madre de Jesús." },
      { name: "José (esposo de María)", desc: "Padre adoptivo de Jesús, carpintero de Nazaret." },
      { name: "Zacarías y Elisabet", desc: "Padres de Juan el Bautista." },
      { name: "Juan el Bautista", desc: "Precursor de Jesús; bautizó en el río Jordán." },
      { name: "Jesús", desc: "El Mesías; centro de los cuatro Evangelios." },
      { name: "Pedro", desc: "Pescador; líder entre los doce apóstoles." },
      { name: "Andrés", desc: "Hermano de Pedro, también apóstol." },
      { name: "Santiago (hijo de Zebedeo)", desc: "Apóstol, hermano de Juan." },
      { name: "Juan (apóstol)", desc: "El 'discípulo amado'; escribió un Evangelio y Apocalipsis." },
      { name: "Felipe (apóstol)", desc: "Uno de los doce apóstoles." },
      { name: "Bartolomé (Natanael)", desc: "Apóstol descrito como 'sin engaño'." },
      { name: "Tomás", desc: "Apóstol que dudó de la resurrección hasta ver las heridas." },
      { name: "Mateo", desc: "Recaudador de impuestos llamado a ser apóstol." },
      { name: "Santiago (hijo de Alfeo)", desc: "Uno de los doce apóstoles." },
      { name: "Tadeo", desc: "Uno de los doce apóstoles." },
      { name: "Simón el Zelote", desc: "Uno de los doce apóstoles." },
      { name: "Judas Iscariote", desc: "Traicionó a Jesús por 30 monedas de plata." },
      { name: "María Magdalena", desc: "Discípula fiel; primer testigo de la resurrección." },
      { name: "Marta", desc: "Hermana de Lázaro y María de Betania." },
      { name: "María de Betania", desc: "Ungió los pies de Jesús con perfume costoso." },
      { name: "Lázaro", desc: "Resucitado por Jesús después de cuatro días de muerto." },
      { name: "Nicodemo", desc: "Fariseo que buscó a Jesús de noche." },
      { name: "La mujer samaritana", desc: "Habló con Jesús junto a un pozo." },
      { name: "Zaqueo", desc: "Recaudador de impuestos transformado por Jesús." },
      { name: "Bartimeo", desc: "Mendigo ciego sanado por Jesús." },
      { name: "El joven rico", desc: "No pudo dejar sus riquezas para seguir a Jesús." },
      { name: "Poncio Pilato", desc: "Gobernador romano que sentenció a Jesús." },
      { name: "Herodes el Grande", desc: "Rey que ordenó matar a los niños de Belén." },
      { name: "Herodes Antipas", desc: "Gobernante que interrogó a Jesús." },
      { name: "Herodías y Salomé", desc: "Causaron la muerte de Juan el Bautista." },
      { name: "Caifás y Anás", desc: "Sumos sacerdotes que juzgaron a Jesús." },
      { name: "Simón de Cirene", desc: "Cargó la cruz de Jesús." },
      { name: "José de Arimatea", desc: "Ofreció su propia tumba para el cuerpo de Jesús." },
      { name: "Barrabás", desc: "Preso liberado en lugar de Jesús." },
      { name: "El buen ladrón", desc: "Creyó en Jesús mientras ambos morían en la cruz." },
    ],
  },
  {
    era: "Hechos y la iglesia primitiva",
    ref: "Hechos, cartas del Nuevo Testamento",
    people: [
      { name: "Matías", desc: "Reemplazó a Judas Iscariote entre los doce." },
      { name: "Esteban", desc: "Primer mártir cristiano, apedreado por su fe." },
      { name: "Felipe el evangelista", desc: "Bautizó al eunuco etíope." },
      { name: "Simón el mago", desc: "Quiso comprar el poder del Espíritu Santo." },
      { name: "El eunuco etíope", desc: "Funcionario bautizado por Felipe en el camino a Gaza." },
      { name: "Cornelio", desc: "Primer gentil bautizado, tras la visión de un ángel." },
      { name: "Ananías de Damasco", desc: "Sanó a Saulo de su ceguera tras su conversión." },
      { name: "Ananías y Safira", desc: "Mintieron al Espíritu Santo sobre el dinero de una venta." },
      { name: "Bernabé", desc: "Compañero de misión de Pablo, 'hijo de consolación'." },
      { name: "Pablo (Saulo de Tarso)", desc: "Perseguidor de cristianos convertido en gran misionero." },
      { name: "Silas", desc: "Compañero de viaje de Pablo." },
      { name: "Timoteo", desc: "Joven discípulo y colaborador cercano de Pablo." },
      { name: "Tito", desc: "Colaborador de Pablo, encargado de la iglesia en Creta." },
      { name: "Lucas", desc: "Médico; autor del Evangelio de Lucas y de Hechos." },
      { name: "Juan Marcos", desc: "Autor del Evangelio de Marcos." },
      { name: "Priscila y Aquila", desc: "Matrimonio que instruyó más plenamente a Apolos." },
      { name: "Apolos", desc: "Predicador elocuente de Alejandría." },
      { name: "Lidia", desc: "Primera convertida en Europa, en la ciudad de Filipos." },
      { name: "Dorcas (Tabita)", desc: "Discípula conocida por su generosidad y caridad." },
      { name: "Agabo", desc: "Profeta que anunció el arresto de Pablo en Jerusalén." },
      { name: "Sergio Paulo", desc: "Procónsul romano que creyó en el evangelio." },
      { name: "Elimas", desc: "Mago que se opuso a la predicación de Pablo." },
      { name: "Gamaliel", desc: "Maestro de la Ley que defendió a los apóstoles ante el Sanedrín." },
      { name: "Herodes Agripa I", desc: "Rey que persiguió a la iglesia primitiva." },
      { name: "Herodes Agripa II y Berenice", desc: "Escucharon la defensa de Pablo." },
      { name: "Félix y Festo", desc: "Gobernadores romanos que juzgaron el caso de Pablo." },
      { name: "Onésimo", desc: "Esclavo fugitivo, tema central de la carta a Filemón." },
      { name: "Filemón", desc: "Dueño cristiano de Onésimo, destinatario de una carta de Pablo." },
      { name: "Epafrodito", desc: "Mensajero y colaborador cercano de Pablo." },
      { name: "Aristarco y Trófimo", desc: "Compañeros de viaje de Pablo." },
      { name: "Tíquico", desc: "Mensajero de confianza de Pablo." },
      { name: "Andrónico y Junias", desc: "Cristianos notables mencionados en la carta a los Romanos." },
      { name: "Febe", desc: "Diaconisa que llevó la carta de Pablo a los Romanos." },
    ],
  },
];

const CHARACTER_GALLERY_EN = [
  {
    era: "Origins: Creation and the first descendants",
    ref: "Genesis 1–11",
    people: [
      { name: "Adam", desc: "The first man, formed by God from the dust of the ground." },
      { name: "Eve", desc: "The first woman, mother of all humanity." },
      { name: "Cain", desc: "Eldest son of Adam and Eve; killed his brother Abel." },
      { name: "Abel", desc: "Second son of Adam and Eve, a keeper of sheep." },
      { name: "Seth", desc: "Son of Adam and Eve, born after Abel's death." },
      { name: "Enosh", desc: "Son of Seth, grandson of Adam." },
      { name: "Enoch", desc: "Walked with God and did not experience death." },
      { name: "Methuselah", desc: "The longest-lived man in the Bible: 969 years." },
      { name: "Lamech", desc: "Father of Noah." },
      { name: "Noah", desc: "Built the ark and survived the flood." },
      { name: "Shem", desc: "Son of Noah, ancestor of the Semitic peoples." },
      { name: "Ham", desc: "Son of Noah." },
      { name: "Japheth", desc: "Son of Noah." },
      { name: "Nimrod", desc: "Mighty hunter, founder of kingdoms including Babel." },
      { name: "Terah", desc: "Father of Abraham." },
    ],
  },
  {
    era: "The Patriarchs and their families",
    ref: "Genesis 12–50",
    people: [
      { name: "Abraham", desc: "Father of faith; left his homeland trusting God's promise." },
      { name: "Sarah", desc: "Abraham's wife, mother of Isaac in her old age." },
      { name: "Lot", desc: "Abraham's nephew; lived in Sodom." },
      { name: "Hagar", desc: "Sarah's servant, mother of Ishmael." },
      { name: "Ishmael", desc: "Son of Abraham and Hagar." },
      { name: "Isaac", desc: "The promised son, nearly offered as a sacrifice by Abraham." },
      { name: "Rebekah", desc: "Isaac's wife, mother of Esau and Jacob." },
      { name: "Esau", desc: "Isaac's eldest son; sold his birthright." },
      { name: "Jacob (Israel)", desc: "Isaac's younger son, father of the twelve tribes of Israel." },
      { name: "Laban", desc: "Jacob's father-in-law and uncle." },
      { name: "Leah", desc: "Jacob's first wife." },
      { name: "Rachel", desc: "Jacob's beloved wife, mother of Joseph and Benjamin." },
      { name: "Bilhah", desc: "Rachel's servant, mother of Dan and Naphtali." },
      { name: "Zilpah", desc: "Leah's servant, mother of Gad and Asher." },
      { name: "Reuben", desc: "Jacob's eldest son, head of one of the twelve tribes." },
      { name: "Simeon", desc: "Son of Jacob and Leah." },
      { name: "Levi", desc: "Son of Jacob; his tribe would become the priestly one." },
      { name: "Judah", desc: "Son of Jacob; King David would descend from his tribe." },
      { name: "Issachar", desc: "Son of Jacob and Leah." },
      { name: "Zebulun", desc: "Son of Jacob and Leah." },
      { name: "Dan", desc: "Son of Jacob and Bilhah." },
      { name: "Naphtali", desc: "Son of Jacob and Bilhah." },
      { name: "Gad", desc: "Son of Jacob and Zilpah." },
      { name: "Asher", desc: "Son of Jacob and Zilpah." },
      { name: "Benjamin", desc: "Youngest son of Jacob and Rachel." },
      { name: "Dinah", desc: "Daughter of Jacob and Leah." },
      { name: "Tamar (Judah's daughter-in-law)", desc: "Ancestor of David, mentioned in Jesus' genealogy." },
      { name: "Joseph", desc: "Sold by his brothers; became governor of Egypt." },
      { name: "Potiphar", desc: "Egyptian official, Joseph's master." },
      { name: "Asenath", desc: "Joseph's Egyptian wife." },
      { name: "Ephraim", desc: "Son of Joseph, head of a tribe." },
      { name: "Manasseh", desc: "Son of Joseph, head of a tribe." },
      { name: "Melchizedek", desc: "Priest-king of Salem who blessed Abraham." },
    ],
  },
  {
    era: "Exodus and the wilderness",
    ref: "Exodus – Deuteronomy",
    people: [
      { name: "Moses", desc: "Deliverer of Israel; received the Law on Mount Sinai." },
      { name: "Aaron", desc: "Moses' brother, Israel's first high priest." },
      { name: "Miriam", desc: "Sister of Moses and Aaron, a prophetess." },
      { name: "Jethro", desc: "Moses' father-in-law, priest of Midian." },
      { name: "Zipporah", desc: "Moses' wife." },
      { name: "Joshua", desc: "Moses' successor; led the conquest of Canaan." },
      { name: "Caleb", desc: "Faithful spy; inherited land in Canaan for his faithfulness." },
      { name: "Korah, Dathan, and Abiram", desc: "Leaders of a rebellion against Moses and Aaron." },
      { name: "Balaam", desc: "Pagan prophet whose donkey spoke to warn him." },
      { name: "Balak", desc: "King of Moab who hired Balaam to curse Israel." },
      { name: "Phinehas", desc: "Aaron's grandson, zealous for God's holiness." },
      { name: "Nadab and Abihu", desc: "Aaron's sons; died for offering unauthorized fire." },
      { name: "Bezalel", desc: "Craftsman who built the tabernacle." },
    ],
  },
  {
    era: "Conquest and Judges",
    ref: "Joshua – Ruth",
    people: [
      { name: "Rahab", desc: "Protected the Israelite spies in Jericho." },
      { name: "Achan", desc: "His disobedience cost a defeat at Ai." },
      { name: "Othniel", desc: "The first judge of Israel." },
      { name: "Ehud", desc: "Left-handed judge who freed Israel from Moab." },
      { name: "Deborah", desc: "Judge and prophetess who led Israel." },
      { name: "Barak", desc: "General who fought alongside Deborah." },
      { name: "Jael", desc: "Killed the enemy general Sisera." },
      { name: "Gideon", desc: "Judge who defeated the Midianites with only 300 men." },
      { name: "Abimelech", desc: "Gideon's son, a usurper king." },
      { name: "Jephthah", desc: "Judge who made a tragic vow to God." },
      { name: "Samson", desc: "Judge of great strength, betrayed by Delilah." },
      { name: "Delilah", desc: "Discovered the secret of Samson's strength." },
      { name: "Ruth", desc: "Faithful Moabite woman, great-grandmother of King David." },
      { name: "Naomi", desc: "Ruth's mother-in-law." },
      { name: "Boaz", desc: "Kinsman-redeemer who married Ruth." },
    ],
  },
  {
    era: "The united kingdom: Samuel, Saul, David, and Solomon",
    ref: "1–2 Samuel, 1 Kings",
    people: [
      { name: "Eli", desc: "Priest and judge; mentor of young Samuel." },
      { name: "Hannah", desc: "Samuel's mother, a woman of constant prayer." },
      { name: "Samuel", desc: "Last judge and a prophet; anointed both Saul and David." },
      { name: "Saul", desc: "The first king of Israel." },
      { name: "Jonathan", desc: "Saul's son, David's loyal friend." },
      { name: "Michal", desc: "Saul's daughter, David's wife." },
      { name: "David", desc: "A shepherd who became king; defeated the giant Goliath." },
      { name: "Goliath", desc: "Philistine giant defeated by David." },
      { name: "Abigail", desc: "Wise woman who later married David." },
      { name: "Bathsheba", desc: "David's wife, mother of Solomon." },
      { name: "Nathan", desc: "Prophet who confronted David over his sin." },
      { name: "Absalom", desc: "David's son who rebelled against him." },
      { name: "Joab", desc: "Commander of David's army." },
      { name: "Abner", desc: "Commander of Saul's army." },
      { name: "Solomon", desc: "Wise king, builder of the Temple in Jerusalem." },
      { name: "The Queen of Sheba", desc: "Visited Solomon drawn by his wisdom." },
    ],
  },
  {
    era: "The divided kingdoms and their prophets",
    ref: "1–2 Kings, 1–2 Chronicles",
    people: [
      { name: "Rehoboam", desc: "Solomon's son; his reign caused the kingdom to split." },
      { name: "Jeroboam", desc: "First king of the northern kingdom, Israel." },
      { name: "Elijah", desc: "Prophet who confronted the prophets of Baal on Mount Carmel." },
      { name: "Ahab", desc: "King of Israel, husband of Jezebel." },
      { name: "Jezebel", desc: "Queen who promoted the worship of Baal." },
      { name: "Obadiah (Ahab's steward)", desc: "Protected a hundred prophets from persecution." },
      { name: "Elisha", desc: "Elijah's successor; performed many miracles." },
      { name: "Naaman", desc: "Syrian general healed of leprosy by Elisha." },
      { name: "Gehazi", desc: "Elisha's servant, punished for his greed." },
      { name: "Jehu", desc: "King who wiped out the house of Ahab." },
      { name: "Athaliah", desc: "Usurping queen of Judah." },
      { name: "Joash", desc: "Boy king rescued from Athaliah." },
      { name: "Hezekiah", desc: "Reforming king of Judah." },
      { name: "Manasseh", desc: "King of Judah who repented after captivity." },
      { name: "Josiah", desc: "King who restored the worship of God in Judah." },
      { name: "Huldah", desc: "Prophetess who confirmed the Book of the Law found in the Temple." },
    ],
  },
  {
    era: "Exile and return",
    ref: "Ezra, Nehemiah, Esther, Daniel",
    people: [
      { name: "Nebuchadnezzar", desc: "King of Babylon; had a dream interpreted by Daniel." },
      { name: "Belshazzar", desc: "King who saw the writing on the wall: 'Mene, Mene, Tekel, Upharsin'." },
      { name: "Darius", desc: "Persian king under whose reign Daniel was thrown to the lions." },
      { name: "Cyrus", desc: "Persian king who allowed the Jews to return to Jerusalem." },
      { name: "Zerubbabel", desc: "Leader who directed the rebuilding of the Temple." },
      { name: "Ezra", desc: "Priest and scribe who taught the Law to the people." },
      { name: "Nehemiah", desc: "Rebuilt the walls of Jerusalem." },
      { name: "Esther", desc: "Jewish queen who risked her life to save her people." },
      { name: "Mordecai", desc: "Esther's cousin and adoptive father." },
      { name: "Haman", desc: "Enemy of the Jews; planned their extermination." },
      { name: "Ahasuerus", desc: "Persian king, Esther's husband." },
      { name: "Vashti", desc: "Queen deposed before Esther." },
    ],
  },
  {
    era: "Wisdom, Psalms, and the minor prophets",
    ref: "Job, Psalms, Proverbs, minor prophets",
    people: [
      { name: "Job", desc: "Righteous man from the land of Uz; kept his faith through great suffering." },
      { name: "Eliphaz, Bildad, and Zophar", desc: "Job's friends who visited to 'comfort' him." },
      { name: "Elihu", desc: "The youngest of Job's friends, who spoke last." },
      { name: "Asaph", desc: "Musician and psalmist, author of several Psalms." },
      { name: "Agur", desc: "Author of the sayings in Proverbs 30." },
      { name: "Hosea", desc: "Prophet whose marriage symbolized God's love for Israel." },
      { name: "Joel", desc: "Prophet who announced a locust plague over Judah." },
      { name: "Amos", desc: "Shepherd from Tekoa called to prophesy." },
      { name: "Obadiah (prophet)", desc: "Author of the shortest book of the Old Testament." },
      { name: "Jonah", desc: "Prophet swallowed by a great fish after fleeing his mission." },
      { name: "Micah", desc: "Announced that the Messiah would be born in Bethlehem." },
      { name: "Nahum", desc: "Prophesied the fall of Nineveh." },
      { name: "Habakkuk", desc: "Questioned God about justice and waited for His answer." },
      { name: "Zephaniah", desc: "Prophet who announced the day of the Lord." },
      { name: "Haggai", desc: "Encouraged the people to rebuild the Temple." },
      { name: "Zechariah (prophet)", desc: "Had visions about the restoration of Jerusalem." },
      { name: "Malachi", desc: "Author of the last book of the Old Testament." },
    ],
  },
  {
    era: "The Gospels: the life of Jesus",
    ref: "Matthew, Mark, Luke, John",
    people: [
      { name: "Mary", desc: "Mother of Jesus." },
      { name: "Joseph (Mary's husband)", desc: "Jesus' adoptive father, a carpenter from Nazareth." },
      { name: "Zechariah and Elizabeth", desc: "Parents of John the Baptist." },
      { name: "John the Baptist", desc: "Forerunner of Jesus; baptized in the Jordan River." },
      { name: "Jesus", desc: "The Messiah; the center of the four Gospels." },
      { name: "Peter", desc: "A fisherman; leader among the twelve apostles." },
      { name: "Andrew", desc: "Peter's brother, also an apostle." },
      { name: "James (son of Zebedee)", desc: "Apostle, brother of John." },
      { name: "John (apostle)", desc: "The 'beloved disciple'; wrote a Gospel and Revelation." },
      { name: "Philip (apostle)", desc: "One of the twelve apostles." },
      { name: "Bartholomew (Nathanael)", desc: "Apostle described as a man 'in whom there is no deceit'." },
      { name: "Thomas", desc: "Apostle who doubted the resurrection until he saw the wounds." },
      { name: "Matthew", desc: "Tax collector called to be an apostle." },
      { name: "James (son of Alphaeus)", desc: "One of the twelve apostles." },
      { name: "Thaddaeus", desc: "One of the twelve apostles." },
      { name: "Simon the Zealot", desc: "One of the twelve apostles." },
      { name: "Judas Iscariot", desc: "Betrayed Jesus for 30 pieces of silver." },
      { name: "Mary Magdalene", desc: "Faithful disciple; first witness of the resurrection." },
      { name: "Martha", desc: "Sister of Lazarus and Mary of Bethany." },
      { name: "Mary of Bethany", desc: "Anointed Jesus' feet with costly perfume." },
      { name: "Lazarus", desc: "Raised by Jesus after four days dead." },
      { name: "Nicodemus", desc: "Pharisee who sought out Jesus at night." },
      { name: "The Samaritan woman", desc: "Spoke with Jesus by a well." },
      { name: "Zacchaeus", desc: "Tax collector transformed by Jesus." },
      { name: "Bartimaeus", desc: "Blind beggar healed by Jesus." },
      { name: "The rich young man", desc: "Could not give up his wealth to follow Jesus." },
      { name: "Pontius Pilate", desc: "Roman governor who sentenced Jesus." },
      { name: "Herod the Great", desc: "King who ordered the killing of the children of Bethlehem." },
      { name: "Herod Antipas", desc: "Ruler who interrogated Jesus." },
      { name: "Herodias and Salome", desc: "Caused the death of John the Baptist." },
      { name: "Caiaphas and Annas", desc: "High priests who put Jesus on trial." },
      { name: "Simon of Cyrene", desc: "Carried Jesus' cross." },
      { name: "Joseph of Arimathea", desc: "Offered his own tomb for Jesus' body." },
      { name: "Barabbas", desc: "Prisoner released in Jesus' place." },
      { name: "The good thief", desc: "Believed in Jesus as they both died on their crosses." },
    ],
  },
  {
    era: "Acts and the early church",
    ref: "Acts, New Testament letters",
    people: [
      { name: "Matthias", desc: "Replaced Judas Iscariot among the twelve." },
      { name: "Stephen", desc: "The first Christian martyr, stoned for his faith." },
      { name: "Philip the evangelist", desc: "Baptized the Ethiopian eunuch." },
      { name: "Simon the magician", desc: "Tried to buy the power of the Holy Spirit." },
      { name: "The Ethiopian eunuch", desc: "Official baptized by Philip on the road to Gaza." },
      { name: "Cornelius", desc: "First Gentile baptized, after an angel's vision." },
      { name: "Ananias of Damascus", desc: "Healed Saul's blindness after his conversion." },
      { name: "Ananias and Sapphira", desc: "Lied to the Holy Spirit about money from a sale." },
      { name: "Barnabas", desc: "Paul's missionary companion, 'son of encouragement'." },
      { name: "Paul (Saul of Tarsus)", desc: "Persecutor of Christians turned great missionary." },
      { name: "Silas", desc: "Paul's traveling companion." },
      { name: "Timothy", desc: "Young disciple and close collaborator of Paul." },
      { name: "Titus", desc: "Paul's collaborator, put in charge of the church in Crete." },
      { name: "Luke", desc: "A physician; author of the Gospel of Luke and Acts." },
      { name: "John Mark", desc: "Author of the Gospel of Mark." },
      { name: "Priscilla and Aquila", desc: "Married couple who instructed Apollos more fully." },
      { name: "Apollos", desc: "Eloquent preacher from Alexandria." },
      { name: "Lydia", desc: "First convert in Europe, in the city of Philippi." },
      { name: "Dorcas (Tabitha)", desc: "Disciple known for her generosity and charity." },
      { name: "Agabus", desc: "Prophet who foretold Paul's arrest in Jerusalem." },
      { name: "Sergius Paulus", desc: "Roman proconsul who believed the gospel." },
      { name: "Elymas", desc: "Magician who opposed Paul's preaching." },
      { name: "Gamaliel", desc: "Teacher of the Law who defended the apostles before the Sanhedrin." },
      { name: "Herod Agrippa I", desc: "King who persecuted the early church." },
      { name: "Herod Agrippa II and Bernice", desc: "Heard Paul's defense." },
      { name: "Felix and Festus", desc: "Roman governors who judged Paul's case." },
      { name: "Onesimus", desc: "Runaway slave, the central subject of the letter to Philemon." },
      { name: "Philemon", desc: "Christian owner of Onesimus, recipient of a letter from Paul." },
      { name: "Epaphroditus", desc: "Messenger and close collaborator of Paul." },
      { name: "Aristarchus and Trophimus", desc: "Traveling companions of Paul." },
      { name: "Tychicus", desc: "Paul's trusted messenger." },
      { name: "Andronicus and Junia", desc: "Notable Christians mentioned in the letter to the Romans." },
      { name: "Phoebe", desc: "Deaconess who carried Paul's letter to the Romans." },
    ],
  },
];
