/**
 * Banco de preguntas de Trivia Bíblica.
 * Organizado en 12 "tiers" (niveles temáticos de dificultad creciente).
 * Los 120 niveles del juego se agrupan de 10 en 10 dentro de cada tier
 * (ver getLevelConfig en game.js), reutilizando y mezclando las preguntas
 * de cada tier con mecánicas (tiempo, vidas, aciertos requeridos) cada vez
 * más exigentes conforme sube el nivel.
 */

const TIER_INFO = {
  1: { name: "Génesis y la Creación", color: "#4caf7d" },
  2: { name: "Los Patriarcas", color: "#5aa9e6" },
  3: { name: "Éxodo y los Mandamientos", color: "#f2b134" },
  4: { name: "Jueces y Reyes", color: "#e07a5f" },
  5: { name: "Sabiduría y Profetas I", color: "#9b5de5" },
  6: { name: "Profetas Mayores y Menores", color: "#00bbf9" },
  7: { name: "Vida de Jesús", color: "#f15bb5" },
  8: { name: "Parábolas y Enseñanzas", color: "#fee440" },
  9: { name: "Apóstoles y Hechos", color: "#00f5d4" },
  10: { name: "Cartas Paulinas", color: "#ff6b6b" },
  11: { name: "Apocalipsis y Profecía", color: "#845ec2" },
  12: { name: "Trivia Experta", color: "#d90429" },
};

const QUESTION_BANK = {
  1: [
    { q: "¿En cuántos días creó Dios el mundo según el Génesis?", options: ["4 días", "6 días", "7 días", "10 días"], correct: 1, ref: "Génesis 1" },
    { q: "¿Cómo se llamaba el primer hombre creado por Dios?", options: ["Adán", "Noé", "Set", "Caín"], correct: 0, ref: "Génesis 2" },
    { q: "¿Cómo se llamaba la primera mujer?", options: ["Rebeca", "Sara", "Eva", "Rut"], correct: 2, ref: "Génesis 2" },
    { q: "¿Quién construyó el arca para salvarse del diluvio?", options: ["Abraham", "Noé", "Moisés", "Lot"], correct: 1, ref: "Génesis 6" },
    { q: "¿Cuántos días y noches llovió durante el diluvio?", options: ["7", "40", "100", "3"], correct: 1, ref: "Génesis 7" },
    { q: "¿Cómo se llamaba el jardín donde vivían Adán y Eva?", options: ["Canaán", "Edén", "Getsemaní", "Gosén"], correct: 1, ref: "Génesis 2" },
    { q: "¿Qué árbol tenía el fruto prohibido en el Jardín del Edén?", options: ["El árbol de la vida", "El árbol del conocimiento del bien y del mal", "La higuera", "El olivo"], correct: 1, ref: "Génesis 2" },
    { q: "¿Quiénes fueron los dos primeros hijos de Adán y Eva?", options: ["Caín y Abel", "Jacob y Esaú", "Set y Enós", "Sem y Cam"], correct: 0, ref: "Génesis 4" },
    { q: "¿Quién mató a su hermano Abel por celos?", options: ["Set", "Caín", "Lamec", "Enoc"], correct: 1, ref: "Génesis 4" },
    { q: "¿Cuántos libros tiene el Antiguo Testamento?", options: ["27", "39", "46", "12"], correct: 1, ref: "Canon bíblico" },
    { q: "¿Quién fue el hijo de Adán y Eva nacido después de la muerte de Abel?", options: ["Set", "Enós", "Enoc", "Lamec"], correct: 0, ref: "Génesis 4-5" },
    { q: "¿Cómo se llamaba el padre de Noé?", options: ["Matusalén", "Lamec", "Enoc", "Set"], correct: 1, ref: "Génesis 5" },
    { q: "¿Cuáles fueron los tres hijos de Noé?", options: ["Sem, Cam y Jafet", "Set, Enós y Cainán", "Rubén, Simeón y Leví", "Gog, Magog y Fut"], correct: 0, ref: "Génesis 6-9" },
    { q: "¿Quién 'caminó con Dios' y no murió, sino que Dios se lo llevó?", options: ["Enoc", "Set", "Noé", "Matusalén"], correct: 0, ref: "Génesis 5:24" },
    { q: "¿En qué monte reposó el arca de Noé según el relato bíblico?", options: ["Sinaí", "Ararat", "Carmelo", "Nebo"], correct: 1, ref: "Génesis 8:4" },
  ],
  2: [
    { q: "¿Cómo se llamaba la esposa de Abraham?", options: ["Rebeca", "Raquel", "Sara", "Lea"], correct: 2, ref: "Génesis 17" },
    { q: "¿Cómo se llamaba el hijo de la promesa de Abraham y Sara?", options: ["Ismael", "Isaac", "Jacob", "Esaú"], correct: 1, ref: "Génesis 21" },
    { q: "¿Cuál era el nombre original de Abraham antes de que Dios se lo cambiara?", options: ["Abram", "Taré", "Nacor", "Lot"], correct: 0, ref: "Génesis 17" },
    { q: "¿Quién fue el hijo de Abraham con la sierva Agar?", options: ["Isaac", "Ismael", "Madián", "Zimram"], correct: 1, ref: "Génesis 16" },
    { q: "¿Cómo se llamaban los hijos gemelos de Isaac?", options: ["Esaú y Jacob", "Caín y Set", "Sem y Cam", "Efraín y Manasés"], correct: 0, ref: "Génesis 25" },
    { q: "¿Cómo se llamó Jacob después de luchar con el ángel?", options: ["Israel", "Judá", "Efraín", "Leví"], correct: 0, ref: "Génesis 32" },
    { q: "¿Cuántos hijos tuvo Jacob, fundadores de las doce tribus de Israel?", options: ["10", "12", "7", "14"], correct: 1, ref: "Génesis 35" },
    { q: "¿Cuál de los hijos de Jacob fue vendido como esclavo por sus hermanos?", options: ["Rubén", "José", "Benjamín", "Judá"], correct: 1, ref: "Génesis 37" },
    { q: "¿A qué país fue llevado José como esclavo y luego llegó a ser gobernador?", options: ["Babilonia", "Egipto", "Asiria", "Persia"], correct: 1, ref: "Génesis 39-41" },
    { q: "¿Qué prenda le regaló Jacob a José, causando envidia entre sus hermanos?", options: ["Una espada de oro", "Una túnica de colores", "Un manto de lino", "Una corona"], correct: 1, ref: "Génesis 37" },
    { q: "¿Quién era el sobrino de Abraham que vivió en Sodoma?", options: ["Lot", "Nacor", "Harán", "Ismael"], correct: 0, ref: "Génesis 13-19" },
    { q: "¿Cómo se llamaba el suegro de Jacob, para quien trabajó pastoreando ovejas?", options: ["Labán", "Taré", "Nacor", "Betuel"], correct: 0, ref: "Génesis 29" },
    { q: "¿Cuál fue el hijo menor de Jacob, hermano de José por parte de madre (Raquel)?", options: ["Benjamín", "Dan", "Neftalí", "Gad"], correct: 0, ref: "Génesis 35" },
    { q: "¿Cómo se llamaba la única hija de Jacob mencionada por nombre en el Génesis?", options: ["Dina", "Tamar", "Séfora", "Milca"], correct: 0, ref: "Génesis 34" },
    { q: "¿Qué hijo de Jacob dio origen a la tribu de la que descendería el rey David?", options: ["Judá", "Rubén", "Leví", "Simeón"], correct: 0, ref: "Génesis 49" },
  ],
  3: [
    { q: "¿Quién guio al pueblo de Israel para salir de Egipto?", options: ["Josué", "Aarón", "Moisés", "Caleb"], correct: 2, ref: "Éxodo 3" },
    { q: "¿En qué río fue puesto Moisés cuando era bebé?", options: ["Jordán", "Éufrates", "Nilo", "Tigris"], correct: 2, ref: "Éxodo 2" },
    { q: "¿Qué vio Moisés arder sin consumirse en el desierto?", options: ["Un altar", "Una zarza", "Una higuera", "Un candelabro"], correct: 1, ref: "Éxodo 3" },
    { q: "¿Cuántas plagas envió Dios sobre Egipto?", options: ["7", "10", "12", "3"], correct: 1, ref: "Éxodo 7-12" },
    { q: "¿Qué mar se abrió para que los israelitas cruzaran?", options: ["El Mar Muerto", "El Mar Rojo", "El Mar de Galilea", "El Mediterráneo"], correct: 1, ref: "Éxodo 14" },
    { q: "¿En qué monte recibió Moisés los Diez Mandamientos?", options: ["Sinaí", "Sion", "Carmelo", "Nebo"], correct: 0, ref: "Éxodo 19-20" },
    { q: "¿Cuántos años vagó el pueblo de Israel por el desierto?", options: ["10", "25", "40", "70"], correct: 2, ref: "Números 14" },
    { q: "¿Qué alimento enviaba Dios cada mañana en el desierto?", options: ["El maná", "Pan de trigo", "Miel", "Codornices únicamente"], correct: 0, ref: "Éxodo 16" },
    { q: "¿Quién fue el hermano de Moisés que hablaba con el Faraón?", options: ["Aarón", "Coré", "Josué", "Nadab"], correct: 0, ref: "Éxodo 4" },
    { q: "¿Quién sucedió a Moisés como líder de Israel?", options: ["Caleb", "Josué", "Finees", "Elí"], correct: 1, ref: "Josué 1" },
    { q: "¿Quién era la hermana de Moisés que vigiló la cesta en el río Nilo?", options: ["Miriam", "Débora", "Séfora", "Rebeca"], correct: 0, ref: "Éxodo 2" },
    { q: "¿Cómo se llamaba el suegro de Moisés, sacerdote de Madián?", options: ["Jetro", "Coré", "Aarón", "Balaam"], correct: 0, ref: "Éxodo 3" },
    { q: "¿Qué dos espías dieron un informe positivo sobre la Tierra Prometida?", options: ["Josué y Caleb", "Aarón y Josué", "Finees y Eleazar", "Coré y Datán"], correct: 0, ref: "Números 13-14" },
    { q: "¿Quién se rebeló contra Moisés y Aarón, siendo tragado por la tierra?", options: ["Coré", "Balaam", "Nadab", "Abiú"], correct: 0, ref: "Números 16" },
    { q: "¿Qué profeta pagano fue contratado para maldecir a Israel, con una burra que habló?", options: ["Balaam", "Balac", "Jetro", "Elifaz"], correct: 0, ref: "Números 22-24" },
  ],
  4: [
    { q: "¿Qué juez de Israel perdió su fuerza al ser traicionado por Dalila?", options: ["Gedeón", "Sansón", "Jefté", "Aod"], correct: 1, ref: "Jueces 16" },
    { q: "¿Quién fue el primer rey de Israel?", options: ["David", "Saúl", "Salomón", "Roboam"], correct: 1, ref: "1 Samuel 10" },
    { q: "¿Qué joven pastor venció al gigante Goliat?", options: ["David", "Jonatán", "Absalón", "Samuel"], correct: 0, ref: "1 Samuel 17" },
    { q: "¿Con qué arma venció David a Goliat?", options: ["Una espada", "Una honda", "Una lanza", "Un arco"], correct: 1, ref: "1 Samuel 17" },
    { q: "¿Qué hijo de David construyó el Templo de Jerusalén?", options: ["Absalón", "Salomón", "Amnón", "Adonías"], correct: 1, ref: "1 Reyes 6" },
    { q: "¿Qué profetisa y jueza gobernó a Israel antes de la monarquía?", options: ["Débora", "Miriam", "Hulda", "Rut"], correct: 0, ref: "Jueces 4" },
    { q: "¿Quién fue el mejor amigo de David, hijo del rey Saúl?", options: ["Jonatán", "Abner", "Joab", "Natán"], correct: 0, ref: "1 Samuel 18" },
    { q: "¿Con quién cometió adulterio el rey David?", options: ["Betsabé", "Abigail", "Mical", "Tamar"], correct: 0, ref: "2 Samuel 11" },
    { q: "¿En cuántos reinos se dividió Israel tras la muerte de Salomón?", options: ["3", "2", "4", "5"], correct: 1, ref: "1 Reyes 12" },
    { q: "¿Qué reina promovió la adoración de Baal, esposa del rey Acab?", options: ["Atalía", "Jezabel", "Ester", "Vasti"], correct: 1, ref: "1 Reyes 16" },
    { q: "¿Qué joven moabita dejó su tierra para seguir a su suegra Noemí?", options: ["Rut", "Orfa", "Rahab", "Tamar"], correct: 0, ref: "Rut 1" },
    { q: "¿Con quién se casó Rut, pariente redentor de Noemí?", options: ["Booz", "Elimelec", "Quelión", "Obed"], correct: 0, ref: "Rut 4" },
    { q: "¿Qué mujer estéril oró fervientemente por un hijo y luego lo dedicó a Dios, siendo este el profeta Samuel?", options: ["Ana", "Elisabet", "Séfora", "Peniná"], correct: 0, ref: "1 Samuel 1" },
    { q: "¿Qué mujer sabia calmó la ira de David y luego se convirtió en su esposa?", options: ["Abigail", "Mical", "Betsabé", "Ahinoam"], correct: 0, ref: "1 Samuel 25" },
    { q: "¿Qué rey de Israel consultó a una médium en Endor?", options: ["Saúl", "David", "Salomón", "Acab"], correct: 0, ref: "1 Samuel 28" },
  ],
  5: [
    { q: "¿Qué profeta fue tragado por un gran pez tras huir del llamado de Dios?", options: ["Jonás", "Elías", "Eliseo", "Amós"], correct: 0, ref: "Jonás 1" },
    { q: "¿A qué ciudad fue enviado Jonás a predicar?", options: ["Babilonia", "Nínive", "Tarsis", "Damasco"], correct: 1, ref: "Jonás 1" },
    { q: "¿Qué profeta subió al cielo en un carro de fuego?", options: ["Eliseo", "Elías", "Isaías", "Samuel"], correct: 1, ref: "2 Reyes 2" },
    { q: "¿Quién recibió una doble porción del espíritu de Elías?", options: ["Eliseo", "Giezi", "Abdías", "Micaías"], correct: 0, ref: "2 Reyes 2" },
    { q: "¿Quién escribió la mayoría de los Salmos?", options: ["Salomón", "David", "Moisés", "Asaf"], correct: 1, ref: "Salmos" },
    { q: "¿Qué profeta fue arrojado al foso de los leones por orar a Dios?", options: ["Daniel", "Ezequiel", "Jeremías", "Isaías"], correct: 0, ref: "Daniel 6" },
    { q: "¿Qué tres jóvenes fueron arrojados al horno de fuego con Daniel?", options: ["Sadrac, Mesac y Abed-nego", "Ananías, Misael y Azarías (otros nombres)", "Gedeón, Barac y Sansón", "Esdras, Nehemías y Zacarías"], correct: 0, ref: "Daniel 3" },
    { q: "¿Qué libro está lleno de proverbios de sabiduría atribuidos a Salomón?", options: ["Eclesiastés", "Proverbios", "Cantares", "Job"], correct: 1, ref: "Proverbios" },
    { q: "¿Qué profeta escribió las Lamentaciones sobre la destrucción de Jerusalén?", options: ["Jeremías", "Ezequiel", "Isaías", "Joel"], correct: 0, ref: "Lamentaciones" },
    { q: "¿Qué Salmo comienza con 'El Señor es mi pastor'?", options: ["Salmo 91", "Salmo 23", "Salmo 100", "Salmo 51"], correct: 1, ref: "Salmo 23" },
    { q: "¿Qué general sirio fue sanado de lepra por el profeta Eliseo al bañarse en el Jordán?", options: ["Naamán", "Ben-adad", "Hazael", "Giezi"], correct: 0, ref: "2 Reyes 5" },
    { q: "¿A qué viuda multiplicó Elías el aceite y la harina?", options: ["La viuda de Sarepta", "La viuda de Naín", "Ana", "Noemí"], correct: 0, ref: "1 Reyes 17" },
    { q: "¿Qué siervo de Eliseo fue castigado con lepra por su codicia?", options: ["Giezi", "Naamán", "Jonatán", "Abdías"], correct: 0, ref: "2 Reyes 5" },
    { q: "¿Qué hombre justo de la tierra de Uz perdió todo pero mantuvo su fe en Dios?", options: ["Job", "Booz", "Nabal", "Barzilai"], correct: 0, ref: "Job 1" },
    { q: "¿Cómo se llamaban los tres amigos que visitaron a Job para consolarlo?", options: ["Elifaz, Bildad y Zofar", "Elí, Samuel y Natán", "Aarón, Hur y Josué", "Elifaz, Barac y Coré"], correct: 0, ref: "Job 2" },
  ],
  6: [
    { q: "¿Cuáles son los cuatro profetas mayores del Antiguo Testamento?", options: ["Isaías, Jeremías, Ezequiel y Daniel", "Oseas, Joel, Amós y Abdías", "Miqueas, Nahúm, Habacuc y Sofonías", "Hageo, Zacarías, Malaquías y Jonás"], correct: 0, ref: "Profetas mayores" },
    { q: "¿Qué profeta vio la visión de los huesos secos que volvían a la vida?", options: ["Ezequiel", "Daniel", "Isaías", "Jeremías"], correct: 0, ref: "Ezequiel 37" },
    { q: "¿Qué profeta anunció el nacimiento virginal del Mesías, 'Emanuel'?", options: ["Isaías", "Miqueas", "Malaquías", "Zacarías"], correct: 0, ref: "Isaías 7" },
    { q: "¿Cuántos profetas menores hay en el Antiguo Testamento?", options: ["10", "12", "15", "8"], correct: 1, ref: "Profetas menores" },
    { q: "¿Qué profeta se casó con una mujer infiel como símbolo del amor de Dios por Israel?", options: ["Oseas", "Joel", "Amós", "Miqueas"], correct: 0, ref: "Oseas 1" },
    { q: "¿Qué profeta anunció una plaga de langostas sobre Judá?", options: ["Joel", "Nahúm", "Habacuc", "Sofonías"], correct: 0, ref: "Joel 1-2" },
    { q: "¿Qué profeta era pastor de ovejas en Tecoa antes de ser llamado por Dios?", options: ["Amós", "Abdías", "Miqueas", "Hageo"], correct: 0, ref: "Amós 1" },
    { q: "¿Cuál es el libro más corto del Antiguo Testamento?", options: ["Abdías", "Nahúm", "Hageo", "Joel"], correct: 0, ref: "Abdías" },
    { q: "¿Qué profeta anunció que el Mesías nacería en Belén?", options: ["Miqueas", "Zacarías", "Malaquías", "Nahúm"], correct: 0, ref: "Miqueas 5" },
    { q: "¿Cuál es el último libro del Antiguo Testamento?", options: ["Hageo", "Zacarías", "Malaquías", "Abdías"], correct: 2, ref: "Malaquías" },
    { q: "¿Qué rey de Babilonia tuvo el sueño de la gran estatua interpretado por Daniel?", options: ["Nabucodonosor", "Belsasar", "Darío", "Ciro"], correct: 0, ref: "Daniel 2" },
    { q: "¿Qué rey vio la escritura misteriosa en la pared 'Mene, Mene, Tekel, Uparsin'?", options: ["Belsasar", "Nabucodonosor", "Darío", "Asuero"], correct: 0, ref: "Daniel 5" },
    { q: "¿Bajo qué rey persa fue Daniel arrojado al foso de los leones?", options: ["Darío", "Ciro", "Asuero", "Artajerjes"], correct: 0, ref: "Daniel 6" },
    { q: "¿Quién fue el escriba fiel que escribía los mensajes del profeta Jeremías?", options: ["Baruc", "Ezequiel", "Semaías", "Urías"], correct: 0, ref: "Jeremías 36" },
    { q: "¿Qué profeta cuestionó a Dios sobre la justicia y esperó su respuesta 'en la atalaya'?", options: ["Habacuc", "Sofonías", "Nahúm", "Hageo"], correct: 0, ref: "Habacuc 2" },
  ],
  7: [
    { q: "¿En qué ciudad nació Jesús?", options: ["Nazaret", "Belén", "Jerusalén", "Caná"], correct: 1, ref: "Lucas 2" },
    { q: "¿Cómo se llamaba la madre de Jesús?", options: ["Elisabet", "Marta", "María", "Ana"], correct: 2, ref: "Mateo 1" },
    { q: "¿Quién bautizó a Jesús en el río Jordán?", options: ["Pedro", "Juan el Bautista", "Andrés", "Felipe"], correct: 1, ref: "Mateo 3" },
    { q: "¿Cuántos discípulos principales (apóstoles) eligió Jesús?", options: ["10", "12", "7", "70"], correct: 1, ref: "Mateo 10" },
    { q: "¿Cuál fue el primer milagro de Jesús, en unas bodas?", options: ["Sanar a un ciego", "Convertir el agua en vino", "Multiplicar los panes", "Calmar la tormenta"], correct: 1, ref: "Juan 2" },
    { q: "¿En qué ciudad creció Jesús?", options: ["Belén", "Cafarnaúm", "Nazaret", "Jericó"], correct: 2, ref: "Lucas 2" },
    { q: "¿Cuántos días ayunó Jesús en el desierto antes de ser tentado?", options: ["7", "40", "3", "12"], correct: 1, ref: "Mateo 4" },
    { q: "¿Qué apóstol negó a Jesús tres veces?", options: ["Juan", "Pedro", "Tomás", "Santiago"], correct: 1, ref: "Mateo 26" },
    { q: "¿Quién traicionó a Jesús por 30 monedas de plata?", options: ["Judas Iscariote", "Tomás", "Simón el Zelote", "Felipe"], correct: 0, ref: "Mateo 26" },
    { q: "¿En qué monte fue crucificado Jesús?", options: ["El Gólgota", "El monte de los Olivos", "El monte Sinaí", "El monte Tabor"], correct: 0, ref: "Juan 19" },
    { q: "¿Quiénes fueron los padres de Juan el Bautista?", options: ["Zacarías y Elisabet", "José y María", "Cleofás y Salomé", "Simeón y Ana"], correct: 0, ref: "Lucas 1" },
    { q: "¿Qué rey ordenó matar a los niños de Belén al enterarse del nacimiento de Jesús?", options: ["Herodes", "Pilato", "Arquelao", "Herodes Antipas"], correct: 0, ref: "Mateo 2" },
    { q: "¿Quién reconoció al niño Jesús como el Mesías en el templo, tomándolo en sus brazos?", options: ["Simeón", "Nicodemo", "Gamaliel", "Zaqueo"], correct: 0, ref: "Lucas 2" },
    { q: "¿Qué visitantes de oriente llevaron oro, incienso y mirra al niño Jesús?", options: ["Los magos (sabios de oriente)", "Los pastores", "Los sacerdotes del templo", "Los discípulos"], correct: 0, ref: "Mateo 2" },
    { q: "¿Qué carpintero de Nazaret fue el padre adoptivo de Jesús?", options: ["José", "Cleofás", "Zacarías", "Alfeo"], correct: 0, ref: "Mateo 1" },
  ],
  8: [
    { q: "¿Cómo se llama el discurso de Jesús que incluye las Bienaventuranzas?", options: ["El Sermón del Monte", "La Gran Comisión", "El discurso del aposento alto", "El Padre Nuestro"], correct: 0, ref: "Mateo 5-7" },
    { q: "En la parábola del hijo pródigo, ¿qué hizo el padre cuando su hijo regresó?", options: ["Lo rechazó", "Lo recibió con una fiesta", "Lo puso a prueba un año", "Lo envió con los sirvientes"], correct: 1, ref: "Lucas 15" },
    { q: "¿Quién ayudó a un hombre herido en la parábola del amor al prójimo?", options: ["Un sacerdote", "Un levita", "El buen samaritano", "Un fariseo"], correct: 2, ref: "Lucas 10" },
    { q: "¿Con cuántos panes y peces alimentó Jesús a 5000 personas?", options: ["5 panes y 2 peces", "7 panes y 3 peces", "2 panes y 5 peces", "10 panes y 1 pez"], correct: 0, ref: "Mateo 14" },
    { q: "¿Qué parábola habla de un pastor que deja 99 ovejas para buscar una perdida?", options: ["La oveja perdida", "La moneda perdida", "El sembrador", "La red"], correct: 0, ref: "Lucas 15" },
    { q: "¿Qué le pidió Jesús a Pedro que hiciera sobre el agua?", options: ["Pescar", "Caminar", "Orar", "Nadar"], correct: 1, ref: "Mateo 14" },
    { q: "¿A quién resucitó Jesús después de cuatro días de muerto?", options: ["Lázaro", "Jairo", "El hijo de la viuda de Naín", "Su padre"], correct: 0, ref: "Juan 11" },
    { q: "¿Qué ungió a los pies de Jesús con perfume costoso?", options: ["María de Betania", "Marta", "Herodías", "Salomé"], correct: 0, ref: "Juan 12" },
    { q: "¿Cuál llamó Jesús 'el mandamiento más grande'?", options: ["Amar a Dios sobre todas las cosas", "No robar", "Guardar el sábado", "Honrar a los padres"], correct: 0, ref: "Mateo 22" },
    { q: "¿Qué instituyó Jesús en la Última Cena con el pan y el vino?", options: ["El bautismo", "La Santa Cena", "El lavado de pies", "El ayuno"], correct: 1, ref: "Lucas 22" },
    { q: "¿Qué recaudador de impuestos de baja estatura se subió a un árbol para ver a Jesús?", options: ["Zaqueo", "Mateo", "Leví", "Simón"], correct: 0, ref: "Lucas 19" },
    { q: "¿Qué fariseo visitó a Jesús de noche para preguntarle cómo nacer de nuevo?", options: ["Nicodemo", "Gamaliel", "Simón el fariseo", "José de Arimatea"], correct: 0, ref: "Juan 3" },
    { q: "¿Con quién habló Jesús junto a un pozo, ofreciéndole 'agua viva'?", options: ["La mujer samaritana", "María Magdalena", "Marta", "La mujer sirofenicia"], correct: 0, ref: "Juan 4" },
    { q: "¿Qué hermanas de Betania, amigas de Jesús, eran hermanas de Lázaro?", options: ["Marta y María", "Salomé y Juana", "Priscila y Lidia", "Ana y Débora"], correct: 0, ref: "Juan 11" },
    { q: "¿En qué parábola un hombre rico ignora a un mendigo llamado Lázaro que yace a su puerta?", options: ["El rico y Lázaro", "El hijo pródigo", "El mayordomo infiel", "El rico insensato"], correct: 0, ref: "Lucas 16" },
  ],
  9: [
    { q: "¿Qué apóstol era pescador junto a su hermano Andrés?", options: ["Pedro", "Mateo", "Tomás", "Judas"], correct: 0, ref: "Mateo 4" },
    { q: "¿Qué apóstol dudó de la resurrección hasta ver las heridas de Jesús?", options: ["Tomás", "Felipe", "Bartolomé", "Santiago"], correct: 0, ref: "Juan 20" },
    { q: "¿Qué día ocurrió el derramamiento del Espíritu Santo sobre los discípulos?", options: ["Pascua", "Pentecostés", "Yom Kipur", "Purim"], correct: 1, ref: "Hechos 2" },
    { q: "¿Quién era Saulo de Tarso antes de convertirse en el apóstol Pablo?", options: ["Un pescador", "Un perseguidor de cristianos", "Un romano pagano", "Un sacerdote del templo"], correct: 1, ref: "Hechos 9" },
    { q: "¿En el camino a qué ciudad Saulo se convirtió?", options: ["Damasco", "Antioquía", "Éfeso", "Corinto"], correct: 0, ref: "Hechos 9" },
    { q: "¿Quién fue el primer mártir cristiano, apedreado por su fe?", options: ["Esteban", "Santiago", "Bernabé", "Felipe"], correct: 0, ref: "Hechos 7" },
    { q: "¿Qué apóstol escribió el libro de Apocalipsis?", options: ["Juan", "Pedro", "Pablo", "Santiago"], correct: 0, ref: "Apocalipsis 1" },
    { q: "¿Quién fue liberado milagrosamente de la cárcel por un ángel?", options: ["Pedro", "Pablo únicamente", "Bernabé", "Silas únicamente"], correct: 0, ref: "Hechos 12" },
    { q: "¿Quién escribió el libro de Hechos, además del Evangelio de Lucas?", options: ["Lucas", "Marcos", "Timoteo", "Tito"], correct: 0, ref: "Hechos 1" },
    { q: "¿Con quién viajó Pablo en su primer viaje misionero, junto a Bernabé?", options: ["Juan Marcos", "Silas", "Timoteo", "Tito"], correct: 0, ref: "Hechos 13" },
    { q: "¿Qué matrimonio murió tras mentir al Espíritu Santo sobre el dinero de una venta?", options: ["Ananías y Safira", "Aquila y Priscila", "Félix y Drusila", "Herodes y Herodías"], correct: 0, ref: "Hechos 5" },
    { q: "¿Qué centurión romano fue el primer gentil bautizado, tras la visión de un ángel?", options: ["Cornelio", "Julio", "Sergio Paulo", "Félix"], correct: 0, ref: "Hechos 10" },
    { q: "¿Qué evangelista bautizó al eunuco etíope en el camino a Gaza?", options: ["Felipe", "Esteban", "Bernabé", "Apolos"], correct: 0, ref: "Hechos 8" },
    { q: "¿Qué matrimonio de tejedores de tiendas ayudó a instruir a Apolos y colaboró con Pablo?", options: ["Priscila y Aquila", "Ananías y Safira", "Andrónico y Junias", "Felipe y su esposa"], correct: 0, ref: "Hechos 18" },
    { q: "¿Qué mujer de Filipos, vendedora de púrpura, fue de las primeras convertidas en Europa?", options: ["Lidia", "Dorcas", "Febe", "Junia"], correct: 0, ref: "Hechos 16" },
  ],
  10: [
    { q: "¿Cuántas cartas se atribuyen tradicionalmente al apóstol Pablo?", options: ["7", "13", "9", "21"], correct: 1, ref: "Cartas paulinas" },
    { q: "¿A qué iglesia fue escrito el 'himno al amor' de 1 Corintios 13?", options: ["Éfeso", "Corinto", "Filipos", "Colosas"], correct: 1, ref: "1 Corintios 13" },
    { q: "¿Cuál NO es uno de los frutos del Espíritu mencionados en Gálatas 5?", options: ["Amor", "Paciencia", "Riqueza", "Templanza"], correct: 2, ref: "Gálatas 5" },
    { q: "¿Quién escribió la carta de Santiago en el Nuevo Testamento?", options: ["Santiago, hermano de Jesús", "Santiago, hijo de Zebedeo", "Pablo", "Judas"], correct: 0, ref: "Santiago 1" },
    { q: "¿Cuántas cartas escribió el apóstol Juan?", options: ["2", "3", "1", "4"], correct: 1, ref: "1, 2 y 3 Juan" },
    { q: "¿Qué apóstol escribió las cartas de 1 y 2 de Pedro?", options: ["Pedro", "Juan", "Andrés", "Felipe"], correct: 0, ref: "1 y 2 Pedro" },
    { q: "¿En qué ciudad estaba preso Pablo cuando escribió varias 'cartas de la prisión'?", options: ["Jerusalén", "Roma", "Atenas", "Antioquía"], correct: 1, ref: "Efesios, Filipenses, Colosenses" },
    { q: "¿Qué describe Pablo en Efesios 6 como protección espiritual del creyente?", options: ["La armadura de Dios", "El fruto del Espíritu", "Los dones espirituales", "El nuevo pacto"], correct: 0, ref: "Efesios 6" },
    { q: "¿A quiénes dirigió Pablo las cartas pastorales 1 y 2 de Timoteo y Tito?", options: ["A sus colaboradores Timoteo y Tito", "A las iglesias de Galacia", "A los ancianos de Jerusalén", "A su familia"], correct: 0, ref: "Cartas pastorales" },
    { q: "¿Qué carta del Nuevo Testamento fue escrita a favor del esclavo Onésimo?", options: ["Filemón", "Colosenses", "Filipenses", "Tito"], correct: 0, ref: "Filemón" },
    { q: "¿Qué predicador elocuente de Alejandría fue instruido más plenamente por Priscila y Aquila?", options: ["Apolos", "Timoteo", "Tito", "Silas"], correct: 0, ref: "Hechos 18" },
    { q: "¿A quién Pablo llamó su 'verdadero hijo en la fe' y le encargó la iglesia en Creta?", options: ["Tito", "Timoteo", "Onésimo", "Epafrodito"], correct: 0, ref: "Tito 1" },
    { q: "¿Quién acompañó a Pablo en su segundo viaje misionero tras la separación de Bernabé?", options: ["Silas", "Juan Marcos", "Lucas únicamente", "Apolos"], correct: 0, ref: "Hechos 15" },
    { q: "¿Qué esclavo fugitivo es el tema central de la carta a Filemón?", options: ["Onésimo", "Ergasto", "Trófimo", "Aristarco"], correct: 0, ref: "Filemón" },
    { q: "¿Qué joven pastor de Listra fue discípulo cercano de Pablo, destinatario de dos cartas pastorales?", options: ["Timoteo", "Tito", "Silas", "Marcos"], correct: 0, ref: "1 y 2 Timoteo" },
  ],
  11: [
    { q: "¿Quién recibió la revelación de Apocalipsis exiliado en la isla de Patmos?", options: ["El apóstol Juan", "El apóstol Pedro", "Pablo", "Bernabé"], correct: 0, ref: "Apocalipsis 1" },
    { q: "¿Cuántas iglesias reciben cartas al inicio de Apocalipsis?", options: ["5", "7", "12", "3"], correct: 1, ref: "Apocalipsis 2-3" },
    { q: "¿Cuántos sellos son abiertos en la visión del rollo en Apocalipsis?", options: ["7", "10", "4", "12"], correct: 0, ref: "Apocalipsis 6" },
    { q: "¿Cómo se conoce a las cuatro figuras que aparecen al abrir los primeros sellos?", options: ["Los cuatro vientos", "Los cuatro jinetes del Apocalipsis", "Los cuatro seres vivientes", "Los cuatro ángeles"], correct: 1, ref: "Apocalipsis 6" },
    { q: "¿Qué número es descrito como 'el número de la bestia' en Apocalipsis?", options: ["777", "666", "333", "888"], correct: 1, ref: "Apocalipsis 13" },
    { q: "¿Cómo se llama la batalla final entre el bien y el mal en Apocalipsis?", options: ["Armagedón", "Jericó", "Éxodo final", "Sinaí"], correct: 0, ref: "Apocalipsis 16" },
    { q: "¿Qué describe Juan al final de Apocalipsis como nueva creación?", options: ["El nuevo cielo y la nueva tierra", "El nuevo templo de Salomón", "El nuevo arca del pacto", "El nuevo Edén terrenal"], correct: 0, ref: "Apocalipsis 21" },
    { q: "¿Cuántos años dura el reinado milenial mencionado en Apocalipsis 20?", options: ["100 años", "1000 años", "40 años", "7 años"], correct: 1, ref: "Apocalipsis 20" },
    { q: "¿Cómo se describe la ciudad santa que desciende del cielo?", options: ["La Nueva Jerusalén", "La Nueva Babilonia", "La Nueva Sion", "La Nueva Belén"], correct: 0, ref: "Apocalipsis 21" },
    { q: "¿Qué representa el árbol de la vida al final de Apocalipsis?", options: ["Riqueza para los reyes", "Sanidad para las naciones", "Sabiduría oculta", "Juicio final"], correct: 1, ref: "Apocalipsis 22" },
    { q: "¿Cómo se describe a la mujer que aparece 'vestida del sol' en Apocalipsis 12?", options: ["Con una corona de doce estrellas y la luna bajo sus pies", "Con una espada de fuego en la mano", "Rodeada de siete candeleros", "Sentada sobre una bestia escarlata"], correct: 0, ref: "Apocalipsis 12" },
    { q: "¿Qué figura simbólica representa al diablo en Apocalipsis, descrita como una gran serpiente roja?", options: ["El gran dragón", "La bestia del mar", "El falso profeta", "El anticristo"], correct: 0, ref: "Apocalipsis 12" },
    { q: "¿Cuántos testigos proféticos aparecen en Apocalipsis 11?", options: ["Dos testigos", "Cuatro testigos", "Siete testigos", "Doce testigos"], correct: 0, ref: "Apocalipsis 11" },
    { q: "¿Qué hace un ángel con la llave del abismo a Satanás en Apocalipsis 20?", options: ["Lo ata por mil años", "Lo destruye para siempre", "Lo envía a la tierra", "Lo convierte en ceniza"], correct: 0, ref: "Apocalipsis 20" },
    { q: "¿Qué título usa Jesús para describirse a sí mismo al principio y al final de Apocalipsis?", options: ["El Alfa y la Omega", "El León de Judá", "El Buen Pastor", "El Cordero inmolado"], correct: 0, ref: "Apocalipsis 1 y 22" },
  ],
  12: [
    { q: "¿Cuántos libros tiene la Biblia protestante en total (AT + NT)?", options: ["66", "73", "39", "27"], correct: 0, ref: "Canon bíblico" },
    { q: "¿Cuál es el libro con más capítulos de la Biblia?", options: ["Salmos", "Isaías", "Génesis", "Jeremías"], correct: 0, ref: "Salmos (150 capítulos)" },
    { q: "¿Cuál es el capítulo más largo de toda la Biblia?", options: ["Salmo 119", "Génesis 1", "Isaías 53", "Apocalipsis 21"], correct: 0, ref: "Salmo 119" },
    { q: "¿Cuál es el versículo más corto de la Biblia?", options: ["'Orad sin cesar'", "'Jesús lloró'", "'Dios es amor'", "'Velad y orad'"], correct: 1, ref: "Juan 11:35" },
    { q: "¿En qué idioma se escribió principalmente el Antiguo Testamento?", options: ["Griego", "Arameo", "Hebreo", "Latín"], correct: 2, ref: "Idiomas bíblicos" },
    { q: "¿En qué idioma se escribió principalmente el Nuevo Testamento?", options: ["Hebreo", "Griego", "Latín", "Arameo"], correct: 1, ref: "Idiomas bíblicos" },
    { q: "¿Cuántos años vivió Matusalén, el hombre más longevo de la Biblia?", options: ["777 años", "969 años", "930 años", "500 años"], correct: 1, ref: "Génesis 5:27" },
    { q: "¿Qué rey pidió a Dios sabiduría en lugar de riquezas?", options: ["David", "Salomón", "Ezequías", "Josías"], correct: 1, ref: "1 Reyes 3" },
    { q: "¿Qué mujer escondió a los espías israelitas en Jericó?", options: ["Rahab", "Débora", "Jael", "Rut"], correct: 0, ref: "Josué 2" },
    { q: "¿Qué apóstol reemplazó a Judas Iscariote entre los doce?", options: ["Matías", "Bernabé", "Silas", "Marcos"], correct: 0, ref: "Hechos 1" },
    { q: "¿Qué reina judía arriesgó su vida para salvar a su pueblo del genocidio planeado por Amán?", options: ["Ester", "Vasti", "Atalía", "Jezabel"], correct: 0, ref: "Ester 4-7" },
    { q: "¿Quién era el primo y padre adoptivo de Ester, que descubrió una conspiración contra el rey?", options: ["Mardoqueo", "Amán", "Asuero", "Hegai"], correct: 0, ref: "Ester 2" },
    { q: "¿Quién reconstruyó las murallas de Jerusalén tras el exilio babilónico?", options: ["Nehemías", "Esdras", "Zorobabel", "Hageo"], correct: 0, ref: "Nehemías 2-6" },
    { q: "¿Quién fue el sacerdote y escriba que enseñó la ley al pueblo tras el regreso del exilio?", options: ["Esdras", "Nehemías", "Josué el sumo sacerdote", "Malaquías"], correct: 0, ref: "Esdras 7" },
    { q: "¿Quién fue el misterioso rey-sacerdote de Salem a quien Abraham entregó el diezmo?", options: ["Melquisedec", "Quedorlaomer", "Abimelec", "Efrón"], correct: 0, ref: "Génesis 14" },
  ],
};
